version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    container_name: community_forum_db
    environment:
      POSTGRES_USER: forumuser
      POSTGRES_PASSWORD: forumpass
      POSTGRES_DB: forumdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: community_forum_web
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://forumuser:forumpass@db:5432/forumdb
      NEXTAUTH_SECRET: your-secret
      NEXTAUTH_URL: http://localhost:3000
    volumes:
      - ..:/app
    working_dir: /app
    command: "npm run dev"

volumes:
  pgdata:
